module.exports = {
    root: true,
    parser: '@typescript-eslint/parser',
    parserOptions: {
        ecmaVersion: 2018,
        ecmaFeatures: {
            legacyDecorators: true,
        },
        sourceType: 'module',
    },
    extends: ['plugin:@typescript-eslint/eslint-recommended', 'prettier', 'prettier/react'],
    plugins: [
        'react',
        '@typescript-eslint',
        'prettier',
        // "jsx-a11y",
        // 'import',
        // 'import-order-autofix',
        // 'sort-keys-fix',
        // 'sort-destructure-keys',
        // '@typescript-eslint/eslint',
    ],
    globals: {
        __DEV__: false,
        jest: false,
        jasmine: false,
        it: false,
        describe: false,
        expect: false,
        element: false,
        by: false,
        beforeAll: false,
        beforeEach: false,
        afterAll: false,
    },
    rules: {
        'prettier/prettier': 'error',
        // 'comma-dangle': 'off',
        // 'array-element-newline': ['error', 'consistent'],
        // 'array-bracket-spacing': ['error', 'always'],
        // 'arrow-parens': ['error', 'as-needed', { requireForBlockBody: false }],
        // 'import/order': [
        //     'error',
        //     {
        //         groups: [['builtin', 'external', 'internal'], ['parent', 'sibling'], 'index'],
        //         'newlines-between': 'always',
        //     },
        // ],
        // 'sort-imports': [
        //     'off',
        //     {
        //         ignoreCase: true,
        //         ignoreMemberSort: false,
        //         memberSyntaxSortOrder: ['none', 'multiple', 'single', 'all'],
        //     },
        // ],
        // 'sort-keys-fix/sort-keys-fix': [
        //     'off',
        //     'asc',
        //     {
        //         caseSensitive: false,
        //         natural: false,
        //     },
        // ],
        // 'react/jsx-sort-default-props': ['warn', { ignoreCase: true }],
        // 'import/no-extraneous-dependencies': 'warn',
        // 'import/prefer-default-export': ['warn'],
        // 'import/no-unresolved': 'off',
        // indent: ['warn', 4],
        // 'no-multi-spaces': ['error', { exceptions: { ImportDeclaration: true } }],
        // 'no-plusplus': 'off',
        // 'no-restricted-syntax': ['error', 'ForInStatement', 'LabeledStatement', 'WithStatement'],
        'no-shadow': 'off',
        // 'no-underscore-dangle': 'off',
        // 'no-unused-expressions': ['error', { allowShortCircuit: true }],
        // 'no-use-before-define': 'off',
        // 'object-property-newline': 'warn',
        // 'react/forbid-prop-types': 'off',
        // 'react/jsx-filename-extension': ['error', { extensions: ['.js'] }],
        // 'react/jsx-first-prop-new-line': ['error', 'multiline'],
        // 'react/jsx-indent': ['warn', 4],
        // 'react/jsx-indent-props': ['warn', 4],
        // 'react/no-unused-prop-types': 'warn',
        // 'react/prefer-stateless-function': 'warn',
        // 'react/jsx-one-expression-per-line': 'error',
        // 'react/sort-prop-types': 'error',
        // 'react/jsx-pascal-case': 'error',
        // 'react/jsx-fragments': 'off',
        // 'react/jsx-max-props-per-line': ['error', { maximum: 1 }],
        // 'react/jsx-closing-bracket-location': ['error', 'line-aligned'],
        // 'react/jsx-wrap-multilines': ['error'],

        // 'sort-destructure-keys/sort-destructure-keys': 'error',
        // 'no-param-reassign': 'off',
    },
};
