# Shared naughty strings for security/path traversal testing in LedFx
# Place all path traversal, special filename, and related test vectors here.

# Path traversal patterns for testing file path validation
naughty_paths = [
    # Classic path traversal with extensions
    "../etc/passwd",
    "../../etc/passwd",
    "../../../etc/passwd",
    "../../../../etc/passwd",
    # With image extension
    "../../../etc/passwd.png",
    "../../etc/shadow.jpg",
    # Windows path traversal
    "..\\..\\..\\Windows\\System32\\config\\SAM",
    "..\\..\\..\\Windows\\System32\\config\\SAM.png",
    # Encoded path traversal
    "%2e%2e%2f%2e%2e%2f%2e%2e%2fetc%2fpasswd",
    "..%2F..%2F..%2Fetc%2Fpasswd",
    # Double encoded
    "%252e%252e%252f%252e%252e%252f%252e%252e%252fetc%252fpasswd",
    # Unicode encoding
    "..%c0%af..%c0%af..%c0%afetc%c0%afpasswd",
    # Various separators
    "....//....//....//etc/passwd",
    "..../..../..../etc/passwd",
    # Null byte injection
    "../../../etc/passwd%00.png",
    "../../../etc/passwd\x00.png",
    # Absolute paths (should be outside allowed dirs)
    "/etc/passwd.png",
    "/etc/shadow.jpg",
    # Windows absolute path removed - not a traversal attempt on Linux
    "/root/.ssh/id_rsa.png",
    # Mixed separators
    "..\\../..\\../etc/passwd",
    "../\\../\\../etc/passwd",
    # Overlong paths
    "." * 1000 + "/etc/passwd.png",
    # Special characters
    "../etc/passwd\n.png",
    "../etc/passwd\r\n.png",
    "../etc/passwd\t.png",
    "../",
    "..\\",
    "..%2f",
    "..%5c",
    "..%252f",
    "..%255c",
    "..%c0%af",
    "..%c1%1c",
    "..%e0%80%af",
    "..%u2215",
    "..%u2216",
    "..%u2044",
    "..%u2215..%u2215",
    "..%u2216..%u2216",
    "..%u2044..%u2044",
    "..%u2215..%u2216",
    "..%u2044..%u2215",
    "..%u2216..%u2044",
    "..%u2215..%u2044",
    "..%u2216..%u2215",
    "..%u2044..%u2216",
    "..%u2044..%u2044",
    "..%c0%ae%c0%ae/",
    "..%c0%ae%c0%ae\\",
    "..%c0%ae%c0%ae%2f",
    "..%c0%ae%c0%ae%5c",
    "..%c0%ae%c0%ae%252f",
    "..%c0%ae%c0%ae%255c",
    "..%c0%ae%c0%ae%2e%2e/",
    "..%c0%ae%c0%ae%2e%2e\\",
    "..%c0%ae%c0%ae%2e%2e%2f",
    "..%c0%ae%c0%ae%2e%2e%5c",
    "..%c0%ae%c0%ae%2e%2e%252f",
    "..%c0%ae%c0%ae%2e%2e%255c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e/",
    "..%c0%ae%c0%ae%2e%2e%2e%2e\\",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%5c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%252f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%255c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e/",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e\\",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%5c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%252f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%255c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e/",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e\\",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%2f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%5c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%252f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%255c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%2e%2e/",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%2e%2e\\",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%2e%2e%2f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%2e%2e%5c",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%2e%2e%252f",
    "..%c0%ae%c0%ae%2e%2e%2e%2e%2e%2e%2e%2e%2e%2e%255c",
    # Windows reserved device names with path context (actual path traversal attempts)
    # Note: Bare reserved names (CON, PRN, etc.) are in naughty_filenames, not here
    "//./../",
    "//?//../",
    # Windows absolute paths removed - not traversal attempts, just platform-specific invalid paths
    "\\.\\C$\\Windows\\System32",
    "\\?\\C:\\Windows\\System32",
    "\\?\\C:\\Windows\\System32\\drivers\\etc\\hosts",
    "\\.\\PhysicalDrive0",
    "\\.\\PhysicalDrive1",
    "\\.\\PhysicalDrive2",
    "\\.\\PhysicalDrive3",
    "\\.\\PhysicalDrive4",
    "\\.\\PhysicalDrive5",
    "\\.\\PhysicalDrive6",
    "\\.\\PhysicalDrive7",
    "\\.\\PhysicalDrive8",
    "\\.\\PhysicalDrive9",
    "\\.\\pipe\\",
    "\\.\\pipe\\testpipe",
    "\\.\\pipe\\testpipe2",
    "\\.\\pipe\\testpipe3",
    "\\.\\pipe\\testpipe4",
    "\\.\\pipe\\testpipe5",
    "\\.\\pipe\\testpipe6",
    "\\.\\pipe\\testpipe7",
    "\\.\\pipe\\testpipe8",
    "\\.\\pipe\\testpipe9",
    "\\.\\pipe\\testpipe10",
    "\\.\\pipe\\testpipe11",
    "\\.\\pipe\\testpipe12",
    "\\.\\pipe\\testpipe13",
    "\\.\\pipe\\testpipe14",
    "\\.\\pipe\\testpipe15",
    "\\.\\pipe\\testpipe16",
    "\\.\\pipe\\testpipe17",
    "\\.\\pipe\\testpipe18",
    "\\.\\pipe\\testpipe19",
    "\\.\\pipe\\testpipe20",
    "\\.\\pipe\testpipe",
    "\\.\\pipe\testpipe2",
    "\\.\\pipe\testpipe3",
    "\\.\\pipe\testpipe4",
    "\\.\\pipe\testpipe5",
    "\\.\\pipe\testpipe6",
    "\\.\\pipe\testpipe7",
    "\\.\\pipe\testpipe8",
    "\\.\\pipe\testpipe9",
    "\\.\\pipe\testpipe10",
    "\\.\\pipe\testpipe11",
    "\\.\\pipe\testpipe12",
    "\\.\\pipe\testpipe13",
    "\\.\\pipe\testpipe14",
    "\\.\\pipe\testpipe15",
    "\\.\\pipe\testpipe16",
    "\\.\\pipe\testpipe17",
    "\\.\\pipe\testpipe18",
    "\\.\\pipe\testpipe19",
    "\\.\\pipe\testpipe20",
    "//./pipe/testpipe",
    "//./pipe/testpipe2",
    "//./pipe/testpipe3",
    "//./pipe/testpipe4",
    "//./pipe/testpipe5",
    "//./pipe/testpipe6",
    "//./pipe/testpipe7",
    "//./pipe/testpipe8",
    "//./pipe/testpipe9",
    "//./pipe/testpipe10",
    "//./pipe/testpipe11",
    "//./pipe/testpipe12",
    "//./pipe/testpipe13",
    "//./pipe/testpipe14",
    "//./pipe/testpipe15",
    "//./pipe/testpipe16",
    "//./pipe/testpipe17",
    "//./pipe/testpipe18",
    "//./pipe/testpipe19",
    "//./pipe/testpipe20",
]

# SSRF and URL injection patterns for testing URL validation
naughty_urls = [
    # Protocol injection
    "http://example.com@127.0.0.1/image.png",
    "http://127.0.0.1@example.com/image.png",
    "http://127.0.0.1%2f@example.com/image.png",
    # Port manipulation
    "http://127.0.0.1:80/image.png",
    "http://127.0.0.1:8080/image.png",
    "http://localhost:80/image.png",
    # IPv6 variants
    "http://[::1]:80/image.png",
    "http://[0:0:0:0:0:0:0:1]/image.png",
    "http://[::ffff:127.0.0.1]/image.png",
    # URL encoding tricks
    "http://127.0.0.1%09/image.png",
    "http://127.0.0.1%0a/image.png",
    "http://127.0.0.1%0d/image.png",
    # Octal representation
    "http://0177.0.0.1/image.png",
    "http://0x7f.0.0.1/image.png",
    # Integer representation
    "http://2130706433/image.png",  # 127.0.0.1 as integer
    # Localhost variations
    "http://localhost/image.png",
    "http://LOCALHOST/image.png",
    "http://127.1/image.png",
]

# Special and reserved filenames for testing filename validation
naughty_filenames = [
    # Reserved names on Windows
    "CON",
    "PRN",
    "AUX",
    "NUL",
    "COM1",
    "COM2",
    "COM3",
    "COM4",
    "COM5",
    "COM6",
    "COM7",
    "COM8",
    "COM9",
    "LPT1",
    "LPT2",
    "LPT3",
    "LPT4",
    "LPT5",
    "LPT6",
    "LPT7",
    "LPT8",
    "LPT9",
    # With extensions
    "CON.png",
    "PRN.jpg",
    "AUX.gif",
    "NUL.png",
    "COM1.jpg",
    "LPT1.png",
    # NTFS alternate data streams
    "test.png::$DATA",
    "image.jpg:hidden.txt",
    # Long filenames
    "A" * 300 + ".png",
    "verylongfilename" * 20 + ".png",
    # Control characters
    "test\x00.png",
    "test\x01\x02\x03.png",
    "null\0byte.png",
    # Unicode homoglyphs
    "іmage.png",  # Cyrillic і instead of latin i
    "imаge.png",  # Cyrillic а instead of latin a
    # Tricky filenames
    "tricky..png",
    "trailingdot.",
    "trailingdot.png.",
]
