name: autofix.ci # must be exactly this: autofix.ci identifies the workflow by name

on:
  pull_request:

permissions:
  contents: read

# A new push makes the running fix obsolete.
concurrency:
  group: autofix-${{ github.ref }}
  cancel-in-progress: true

jobs:
  autofix:
    uses: LedFx/.github/.github/workflows/autofix.yml@0e36d944516fe8bd95be7afd5cf9a117f08d5652 # main
