; Script generated by the HM NIS Edit Script Wizard. And edited by @PastaLaPate.
Unicode true
!include FileFunc.nsh
!include LogicLib.nsh
!include Sections.nsh
!include x64.nsh

; HM NIS Edit Wizard helper defines
!define PRODUCT_NAME "LedFx"
; /DPRODUCT_VERSION=X.X.X parameter
!ifndef PRODUCT_VERSION
!define PRODUCT_VERSION "x.x.x"
!endif
!define PRODUCT_PUBLISHER "LedFx"
!define PRODUCT_WEB_SITE "https://ledfx.app"
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\LedFx.exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PRODUCT_NAME}"
!define PRODUCT_UNINST_ROOT_KEY "HKLM"

; MUI 1.67 compatible ------
!include "MUI.nsh"

; MUI Settings
!define MUI_ABORTWARNING
!define MUI_ICON ".\icons\install_icon.ico"
!define MUI_UNICON ".\icons\uninstall_icon.ico"

; Welcome page
!insertmacro MUI_PAGE_WELCOME
; License page
!define MUI_LICENSEPAGE_RADIOBUTTONS
!insertmacro MUI_PAGE_LICENSE "..\LICENSE.txt"
; Components page
!insertmacro MUI_PAGE_COMPONENTS
; Directory page
!insertmacro MUI_PAGE_DIRECTORY
; Instfiles page
!insertmacro MUI_PAGE_INSTFILES
; Finish page
!define MUI_FINISHPAGE_RUN
!define MUI_FINISHPAGE_RUN_FUNCTION RunLedFx
!define MUI_FINISHPAGE_SHOWREADME "https://docs.ledfx.app/en/stable/configuring.html"
!insertmacro MUI_PAGE_FINISH

; Uninstaller pages
!insertmacro MUI_UNPAGE_INSTFILES

; Language files
!insertmacro MUI_LANGUAGE "English"

; MUI end ------

; The setup runs as admin. Start LedFx through Explorer so it runs as the
; signed-in user, with their config, instead of inheriting admin rights.
Function RunLedFx
  Exec '"$WINDIR\explorer.exe" "$INSTDIR\LedFx.exe"'
FunctionEnd

; A running LedFx (tray included) locks its files, so close it first.
; Windows won't open a running exe for writing, which is how we detect it.
!macro CLOSE_LEDFX un
Function ${un}CloseLedFx
  ${IfNot} ${FileExists} "$INSTDIR\LedFx.exe"
    Return
  ${EndIf}
  ClearErrors
  FileOpen $0 "$INSTDIR\LedFx.exe" a
  ${IfNot} ${Errors}
    FileClose $0
    Return
  ${EndIf}
  MessageBox MB_OKCANCEL|MB_ICONEXCLAMATION "LedFx is running. Click OK to close it and continue." /SD IDOK IDOK +2
  Abort
  ; 64-bit PowerShell: a 32-bit one can't read the path of a 64-bit process.
  ${DisableX64FSRedirection}
  nsExec::Exec `"$SYSDIR\WindowsPowerShell\v1.0\powershell.exe" -NoProfile -Command "Get-Process LedFx -ErrorAction SilentlyContinue | Where-Object Path -eq '$INSTDIR\LedFx.exe' | Stop-Process -Force"`
  Pop $0
  ${EnableX64FSRedirection}
  Sleep 2000
  ClearErrors
  FileOpen $0 "$INSTDIR\LedFx.exe" a
  ${If} ${Errors}
    MessageBox MB_ICONSTOP "Couldn't close LedFx. Quit it from its tray icon, then try again." /SD IDOK
    Abort
  ${EndIf}
  FileClose $0
FunctionEnd
!macroend
!insertmacro CLOSE_LEDFX ""
!insertmacro CLOSE_LEDFX "un."

!macro REMOVE_SHORTCUTS
  Delete "$SMPROGRAMS\LedFx\Uninstall.lnk"
  Delete "$SMPROGRAMS\LedFx\Website.lnk"
  Delete "$SMPROGRAMS\LedFx\LedFx.lnk"
  RMDir "$SMPROGRAMS\LedFx"
  Delete "$DESKTOP\LedFx.lnk"
!macroend

Name "${PRODUCT_NAME} ${PRODUCT_VERSION}"
OutFile "ledfx-setup-win-${PRODUCT_VERSION}.exe"
RequestExecutionLevel admin
InstallDir "$PROGRAMFILES64\LedFx"
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show
; A file that can't be written fails the install instead of being skipped.
AllowSkipFiles off

Section "LedFx" SEC01
  SectionIn RO
  SetOutPath "$INSTDIR"
  Call CloseLedFx
  ; Replace the previous version's files outright: stale ones can break it.
  ${If} ${FileExists} "$INSTDIR\_internal\*.*"
    ClearErrors
    RMDir /r "$INSTDIR\_internal"
    ${If} ${Errors}
      Abort "Couldn't remove the previous version from $INSTDIR\_internal. Close any program using it, then try again."
    ${EndIf}
  ${EndIf}
  ; Re-added below if "Start on login" is still ticked.
  DeleteRegValue HKLM "Software\Microsoft\Windows\CurrentVersion\Run" "LedFx"
  File ".\..\dist\LedFx\LedFx.exe"
  ; A per-machine install gets all-users shortcuts. Older installers put
  ; them in the profile of whoever ran the setup, so remove those first.
  !insertmacro REMOVE_SHORTCUTS
  SetShellVarContext all
  CreateDirectory "$SMPROGRAMS\LedFx"
  CreateShortCut "$SMPROGRAMS\LedFx\LedFx.lnk" "$INSTDIR\LedFx.exe"
  CreateShortCut "$DESKTOP\LedFx.lnk" "$INSTDIR\LedFx.exe"
  CreateDirectory "$INSTDIR\_internal"
  SetOutPath "$INSTDIR\_internal"
  File /a /r ".\..\dist\LedFx\_internal\"
SectionEnd


Section /o "Start on login" SEC02
  SetRegView 64
  WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Run" "LedFx" '"$InstDir\LedFx.exe"'
SectionEnd

Section -AdditionalIcons
  WriteIniStr "$INSTDIR\${PRODUCT_NAME}.url" "InternetShortcut" "URL" "${PRODUCT_WEB_SITE}"
  CreateShortCut "$SMPROGRAMS\LedFx\Website.lnk" "$INSTDIR\${PRODUCT_NAME}.url"
  CreateShortCut "$SMPROGRAMS\LedFx\Uninstall.lnk" "$INSTDIR\uninst.exe"
SectionEnd

Section -Post
  SetRegView 64
  WriteUninstaller "$INSTDIR\uninst.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\LedFx.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayName" "$(^Name)"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "UninstallString" '"$INSTDIR\uninst.exe"'
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "QuietUninstallString" '"$INSTDIR\uninst.exe" /S'
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoModify" 1
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "NoRepair" 1
  ${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  WriteRegDWORD ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "EstimatedSize" $0
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayIcon" "$INSTDIR\LedFx.exe"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "URLInfoAbout" "${PRODUCT_WEB_SITE}"
  WriteRegStr ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}" "Publisher" "${PRODUCT_PUBLISHER}"
SectionEnd

Function .onInit
  SetRegView 64
  ; Keep "Start on login" ticked on upgrade if it was on.
  ReadRegStr $0 HKLM "Software\Microsoft\Windows\CurrentVersion\Run" "LedFx"
  ${If} $0 != ""
    !insertmacro SelectSection ${SEC02}
  ${EndIf}
FunctionEnd

; Section descriptions
!insertmacro MUI_FUNCTION_DESCRIPTION_BEGIN
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC01} ""
  !insertmacro MUI_DESCRIPTION_TEXT ${SEC02} ""
!insertmacro MUI_FUNCTION_DESCRIPTION_END


Function un.onUninstSuccess
  HideWindow
  MessageBox MB_ICONINFORMATION|MB_OK "$(^Name) was successfully removed from your computer." /SD IDOK
FunctionEnd

Function un.onInit
  SetRegView 64
  MessageBox MB_ICONQUESTION|MB_YESNO|MB_DEFBUTTON2 "Are you sure you want to completely remove $(^Name) and all of its components?" /SD IDYES IDYES +2
  Abort
FunctionEnd

Section Uninstall
  SetRegView 64
  Call un.CloseLedFx
  Delete "$INSTDIR\${PRODUCT_NAME}.url"
  Delete "$INSTDIR\uninst.exe"
  RMDir /r "$INSTDIR\_internal"
  Delete "$INSTDIR\LedFx.exe"

  SetShellVarContext all
  !insertmacro REMOVE_SHORTCUTS
  RMDir "$INSTDIR"

  DeleteRegKey ${PRODUCT_UNINST_ROOT_KEY} "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
  DeleteRegValue HKLM "Software\Microsoft\Windows\CurrentVersion\Run" "LedFx"
  SetAutoClose true
SectionEnd